version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./dbvol:/data/db
  app:
    build: .
    container_name: app
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo